FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install  \
    && npm install @mui/material @emotion/react @emotion/styled @mui/icons-material \
    && npm i -D react-router-dom

# Copy the rest of the application code to the container
COPY . .

# Build the React app
RUN npm run build

# Install `serve` to serve the build folder
RUN npm install -g serve
# Set the command to serve the application
CMD ["serve", "-s", "build", "-l", "3000"]

# Expose the port the app runs on
EXPOSE 3000
