version: '3.9'

services:
  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "8081:443"
      - "8080:80"
    volumes:
      - ./frontend/src:/app
    networks:
      - frontend-tier
  backend:
    build:
      context: backend-sql
    container_name: backend-sql
    depends_on:
      - movieplexxdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://movieplexxdb:5432/movieplexx
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=test
    ports:
      - "5433:8080"
    networks:
      - data-tier
      - frontend-tier


  movieplexxdb:
    image: postgres:14-alpine
    volumes:
      - movieplexxdata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=movieplexx'
      - 'POSTGRES_PASSWORD=test'
    networks:
      - data-tier

volumes:
  movieplexxdata:

networks:
  data-tier:
    driver: bridge
  frontend-tier:
    driver: bridge
